### ISSUE TITLE
after repeatmasker TELR fails with an error "/bin/sh: 1: file_name.realign.sort.bam: not found"

### ISSUE THREAD

**Issue by SergeiF1987** [bergmanlab/TELR#16]
Hi Shunhua,

Thank you for this software! At the first glance, it has everything that I was looking for identification of TE insertions including allele frequency. Test run passed successfully but when I use my own data it fails with an error which looks like this:

```
analyzing file /mnt/raid/sergey/bio-first/insertion_analysis/test/output/intermediate_files/101N_passed.part-01.te.fa
identifying matches to dvir_full-size_TEs.fasta sequences in batch 1 of 1
processing output:
cycle 1
cycle 2
cycle 3
cycle 4
cycle 5
cycle 6
cycle 7
cycle 8
cycle 9
cycle 10
Generating output...
masking
done
Done

Successfully created the directory /mnt/raid/sergey/bio-first/insertion_analysis/test/output/intermediate_files/telr_reads

Usage: samtools depth [options] in1.bam [in2.bam [...]]
Options:
-a output all positions (including zero depth)
-a -a (or -aa) output absolutely all positions, including unused ref. sequences
-b list of positions or regions
-f list of input BAM filenames, one per line [null]
-l read length threshold (ignore reads shorter than ) [0]
-d/-m maximum coverage depth [8000]. If 0, depth is set to the maximum
integer value, effectively removing any depth limit.
-q base quality threshold [0]
-Q mapping quality threshold [0]
-r chr:from-to region
--input-fmt-option OPT[=VAL]
Specify a single input file format option in the form
of OPTION or OPTION=VALUE
--reference FILE
Reference sequence FASTA FILE [null]

The output is a simple tab-separated table with three columns: reference name,
position, and coverage depth. Note that positions with zero coverage may be
omitted by default; see the -a option.

/bin/sh: 1: _137386_137390:5972-6022: not found
/bin/sh: 1: _137386_137390.realign.sort.bam: not found
Traceback (most recent call last):
File "/mnt/raid/sergey/miniconda/envs/TELR/bin/telr", line 10, in
sys.exit(main())
File "/mnt/raid/sergey/miniconda/envs/TELR/lib/python3.6/site-packages/telr/telr.py", line 129, in main
args.thread,
File "/mnt/raid/sergey/miniconda/envs/TELR/lib/python3.6/site-packages/telr/TELR_te.py", line 677, in get_af
bam, contig_name, start, end, te_interval_size, te_offset
File "/mnt/raid/sergey/miniconda/envs/TELR/lib/python3.6/site-packages/telr/TELR_te.py", line 839, in get_te_cov
start + te_offset + te_interval_size,
File "/mnt/raid/sergey/miniconda/envs/TELR/lib/python3.6/site-packages/telr/TELR_te.py", line 867, in get_median_cov
median_cov = statistics.median(covs)
File "/mnt/raid/sergey/miniconda/envs/TELR/lib/python3.6/statistics.py", line 380, in median
raise StatisticsError("no median for empty data")
statistics.StatisticsError: no median for empty data
```

Could you take a look at this issue?

Thanks in advance! 
Best,
Sergei

**Comment by SergeiF1987** [comment]
> * @SergeiF1987 Thanks for opening this issue!
> * My initial impression is that the issue may be caused by input files naming or formatting, but I need more information to confirm whether this is the case for your run.
> * For the real data run, could you share the `TELR.log` file under the TELR output directory?
> * Are the output messages you posted in [after repeatmasker TELR fails with an error "/bin/sh: 1: file_name.realign.sort.bam: not found" #16 (comment)](https://github.com/bergmanlab/TELR/issues/16#issue-1023823029) from the complete standard output/errors? If not, could you share the complete standard output/errors with me? These files should help me better understand what the problem is. If the message file is too large, you could send it to my gmail address (hanshunhua0829).
> * Thanks a lot!

thanks for so quick reply!
I have attached the log file.
[TELR.log](https://github.com/bergmanlab/TELR/files/7330828/TELR.log)

Not sure I understand where to find the complete standard output/errors. My TELR run created only a folder "intermediate_files" and 2 files - "log" and "loci_eval.tsv". I'm able to share everything you need but could you specify what kind of file do you want me to share? 

Best,
Sergei
