### ISSUE TITLE
ValueError: start out of range

### ISSUE THREAD

**Issue by thamala** [bergmanlab/TELR#24]
Hi,

I’m running TELR on 20 samples sequenced with ONT. Most of them work fine, but few keep failing at the "Estimating allele frequency...” stage.

Here’s the error I’m getting:

```
Traceback (most recent call last):
  File "/gpfs01/home/mbztth/.conda/envs/mamba/envs/TELR/bin/telr", line 8, in <module>
    sys.exit(main())
  File "/gpfs01/home/mbztth/.conda/envs/mamba/envs/TELR/lib/python3.7/site-packages/telr/telr.py", line 129, in main
    args.thread,
  File "/gpfs01/home/mbztth/.conda/envs/mamba/envs/TELR/lib/python3.7/site-packages/telr/TELR_te.py", line 596, in get_af
    vcf_parsed, out, sample_name, bam, raw_reads, telr_reads_dir, read_type="all"
  File "/gpfs01/home/mbztth/.conda/envs/mamba/envs/TELR/lib/python3.7/site-packages/telr/TELR_assembly.py", line 405, in prep_assembly_inputs
    for read in samfile.fetch(ins_chr, start, end):
  File "pysam/libcalignmentfile.pyx", line 1081, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 691, in pysam.libchtslib.HTSFile.parse_region
ValueError: start out of range (-610)
```

**Comment by thamala** [comment]
That worked. Thanks!
